# Generated by Django 4.2.6 on 2023-12-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
